##
# docker-compose.yml
#
# ```
# $ alias dkc=docker-compose
# $ cp .env.default .env
# $ vi .env
# $ dkc config
# ```
#
# @license Apache-2.0
# @maintainer <github.com/farwish>
# @guide: https://docs.docker.com/compose/compose-file/
##

version: '3'

services:
  nginx:
    image: nginx:${IMG_NGINX_VERSION}
    container_name: nginx-con
    volumes:
      - /etc/localtime:/etc/localtime
      - ${DKC_AP}/etc/timezone:/etc/timezone
      - ${DKC_AP}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DKC_AP}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ${DKC_AP}/nginx/cert:/etc/nginx/cert
      - ${DKC_AP}/web:${CONTAINER_WEB_AP}
      - /var/log/nginx/:/var/log/nginx/
    ports:
      - 80:80
      - 81:81
      - 82:82
      - 443:443
    depends_on:
      - php
    restart: on-failure
    networks:
      - default_net

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: ${IMG_MYSQL_VERSION}
    container_name: mysql-con
    environment:                        # 相当于命令行中的环境变量 docker run -e KEY=VAL
      MYSQL_ROOT_PASSWORD: ${_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${_MYSQL_DATABASE}
    volumes:
      - /etc/localtime:/etc/localtime
      - ${DKC_AP}/etc/timezone:/etc/timezone
      - /var/lib/docker/volumes/mysql:/var/lib/mysql
      - ${DKC_AP}/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
    ports:
      - ${HOST_MYSQL_PORT}:3306
    restart: on-failure
    image: phvia/mysql:${IMG_MYSQL_VERSION}     # For tag
    networks:
      - default_net

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        REDIS_VERSION: ${IMG_REDIS_VERSION}
    container_name: redis-con
    volumes:
      - /etc/localtime:/etc/localtime
      - ${DKC_AP}/etc/timezone:/etc/timezone
      - /var/lib/docker/volumes/redis:/data
    ports:
      - ${HOST_REDIS_PORT}:6379
    sysctls:
      net.core.somaxconn: 1024
    restart: on-failure
    image: phvia/redis:${IMG_REDIS_VERSION}
    networks:
      - default_net

  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${IMG_PHP_VERSION}
    container_name: php-con
    volumes:
      - /etc/localtime:/etc/localtime
      - ${DKC_AP}/etc/timezone:/etc/timezone
      - ${DKC_AP}/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${DKC_AP}/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${DKC_AP}/web:${CONTAINER_WEB_AP}
    ports:
      - ${HOST_PHP_PORT}:9000
    depends_on:
      - mysql
    restart: on-failure
    image: phvia/php-fpm:${IMG_PHP_VERSION}
    networks:
      - default_net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${IMG_PHP_VERSION}
        WEB_PATH: ${CONTAINER_WEB_AP}
    container_name: web-con
    volumes:
      - /etc/localtime:/etc/localtime
      - ${DKC_AP}/etc/timezone:/etc/timezone
      - ${DKC_AP}/web:${CONTAINER_WEB_AP}
    depends_on:
      - php
    restart: on-failure
    image: phvia/web:${IMG_PHP_VERSION}
    networks:
      - default_net

  fe:
    build:
      context: ./web
      dockerfile: Dockerfile-fe
      args:
        PHP_VERSION: ${IMG_PHP_VERSION}
        WEB_PATH: ${CONTAINER_WEB_AP}
    container_name: fe-con
    volumes:
      - /etc/localtime:/etc/localtime
      - ${DKC_AP}/etc/timezone:/etc/timezone
      - ${DKC_AP}/web:${CONTAINER_WEB_AP}
    depends_on:
      - php
    image: phvia/fe:10.x
    networks:
      - default_net

networks:
  default_net:
    driver: bridge

